systems:
  basedir: "logs/"
  vis_every: 5000
  add_timestamp: False
  seed: 38

model:
  model_name: "HexPlane"
  time_grid_init: 1
  time_grid_final: 1066 # dummy parameter, is overwritten with the number of frames
  upsampling_type: aligned
  upsample_list: [20000, 40000, 80000]
  update_emptymask_list: [30000, 50000, 90000, 120000]

  depth_loss: False
  depth_loss_weight: 0.01

  fea2denseAct: relu

  TV_t_s_ratio: 20

  TV_weight_density: 0.005
  TV_weight_app: 0.0005

  fusion_one: "multiply"
  fusion_two: "multiply"
  init_scale: 0.9
  init_shift: 0.5
  density_dim: 8
  DensityMode: "general_MLP"

data:
  dataset_name: slam
  scene_bbox_min: [-1.0, -1.0, -1.0]
  scene_bbox_max: [1.0, 1.0, 1.0]
  N_vis: -1

  datasampler_type: images # currently model only adapted for this
  key_f_num: 30
  downsample: 1.0

  cal_fine_bbox: True

optim:
  n_iters: 200000
  batch_size: 1024
  lr_decay_step: 100000 # does not equal n_iters as this is only for the NeRF optim

render_only: False
render_test: True
render_path: False
expname: tum_rgbd
